print("hello wored , this is a whole new python script")
print("hey , ee've added some new changes!!")
print("hey, we add a dog functionality here!!")
print("this is the change that i really wanna save")
print("this is not the change")
